    name: Publish NuGet Package

    on:
      push:
        branches:
          - pack # Or your desired branch for triggering the publish

    jobs:
      publish:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup .NET
            uses: actions/setup-dotnet@v3
            with:
              dotnet-version: '9.0' # Specify your .NET version

          - name: Restore dependencies
            run: dotnet restore

          - name: Build the project
            run: dotnet build --configuration Release --no-restore

          - name: Pack the NuGet package
            run: |
                 dotnet pack EGO.Nimozyn/EGO.Nimozyn.csproj --configuration Release --no-build --output .


          - name: Push to NuGet.org
            run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
